name: Deploy pages

on:
  push:
    branches:
      - main
jobs:
  build-doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Configure pages
        uses: actions/configure-pages@v4

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v4

      - name: Deploy pages
        uses: actions/deploy-pages@v4
